# kustomize/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Point to the Base
resources:
- ../../base

# Apply the Patch
patches:
- path: replica_patch.yaml
