apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-db
  name: todo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-db
    spec:
      containers:
      - image: postgresql:13-el9
        name: postgresql
        resources: {}
status: {}
