apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-backend.yaml 
- service-backend.yaml 
- deployment-frontend.yaml 
- service-frontend.yaml 
- deployment-db.yaml 
- service-db.yaml 
